Added Sorting Algorithm Visulizer Using Pygame
ShehrozIrfan/learn-dsa pull request #62
Opened 2023-10-22 06:36 UTC by Ctoic

Also implemented Likedlist in python.

2023-10-22 09:47 UTC, ShehrozIrfan requested changes
Overall, looks good.
Just need to make a minor change for folder structure.

2023-10-22 09:47 UTC, ShehrozIrfan commented on Sorting_visualization/Sort_vi.py
> +import pygame
Please add this file in the right folder:
`Python/Sorting_visualization/Sort_vi.py`

2023-10-22 10:04 UTC, Ctoic commented
I have now moved the code to the Python directory please check and merge it.

2023-10-22 12:25 UTC, Ctoic commented
Dear @ShehrozIrfan  kindly merge my pull request. I have added the directory in python.

2023-10-23 18:35 UTC, ShehrozIrfan approved these changes
LGTM

2023-10-23 18:35 UTC, merged

2023-10-23 18:35 UTC, ShehrozIrfan commented
Great 🚀

Have fun!